### ISSUE TITLE
Feature: Profile Page

### ISSUE THREAD

**Issue by BosEriko** [kuru-studio/kuru-studio-social-web#11]
# Epic Title

Feature: Profile Page

## Epic Description

This Feature will add a profile page to the website.

## List of Tasks (Complete in order)

1. [x] [Task: API endpoint for a single user](https://github.com/kuru-studio/kuru-studio-social-web/issues/12)
2. [ ] [Task: API endpoint for a single user](https://github.com/kuru-studio/kuru-studio-social-web/issues/12)
3. [ ] [Task: API endpoint for a single user](https://github.com/kuru-studio/kuru-studio-social-web/issues/12)
4. [ ] [Task: API endpoint for a single user](https://github.com/kuru-studio/kuru-studio-social-web/issues/12)
5. [ ] [Task: API endpoint for a single user](https://github.com/kuru-studio/kuru-studio-social-web/issues/12)
